version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
